{
  "swagger": "2.0",
  "info": {
    "version": "1.0.1",
    "title": "AzureGroupsLimited",
    "description": "Azure Active Directory Groups limited scopes and operations.",
    "contact": {
      "name": "Microsoft",
      "url": "https://support.microsoft.com"
    }
  },
  "host": "graph.microsoft.com",
  "schemes": [
    "https"
  ],
  "paths": {
    "/v1.0/groups/{id}": {
      "get": {
        "summary": "Get group",
        "description": "Get details for a group.",
        "operationId": "GetGroup",
        "deprecated": false
      }
    },
    "/v1.0/groups/{id}/members": {
      "get": {
        "summary": "Get group members",
        "description": "Get the users who are members of a group.",
        "operationId": "GetGroupMembers",
        "deprecated": false
      }
    },
    "/v1.0/groups/{groupId}/members/{memberId}/$ref": {
      "delete": {
        "summary": "Remove Member From Group",
        "description": "Remove Member From Group",
        "operationId": "RemoveMemberFromGroup",
        "deprecated": false
      }
    },
    "/v1.0/groups/{id}/members/$ref": {
      "post": {
        "summary": "Add user to group",
        "description": "Add a user to a group in this AAD tenant.",
        "operationId": "AddUserToGroup",
        "deprecated": false
      }
    },
    "/v1.0/groups": {
      "get": {
        "summary": "Find group",
        "description": "Find group by attributes",
        "operationId": "FindGroup",
        "deprecated": false
      },
      "post": {
        "summary": "Create security group",
        "description": "Create a security group in your AAD tenant.",
        "operationId": "CreateSecurityGroup",
        "deprecated": false
      }
    }
  },
  "securityDefinitions": {
    "oauth2-auth": {
      "type": "oauth2",
      "flow": "accessCode",
      "tokenUrl": "https://login.windows.net/common/oauth2/authorize",
      "scopes": {
        "Group.ReadWrite.All": "Group.ReadWrite.All",
        "GroupMember.ReadWrite.All": "GroupMember.ReadWrite.All",
        "offline_access": "offline_access"
      },
      "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize"
    },
    "oAuthClientCredentials": {
      "type": "oauth2",
      "flow": "application",
      "tokenUrl": "https://login.windows.net/common/oauth2/authorize",
      "scopes": {
        "Group.ReadWrite.All": "Group.ReadWrite.All",
        "GroupMember.ReadWrite.All": "GroupMember.ReadWrite.All",
        "offline_access": "offline_access"
      }
    }
  },
  "basePath": "/",
  "security": [
    {
      "oauth2-auth": [
        "Group.ReadWrite.All",
        "GroupMember.ReadWrite.All",
        "offline_access"
      ]
    }
  ]
}